const colorPrefill = 'rgba(0,0,0,0)';
const colorFill = 'rgba(0,0,0,0.5)';

const configMap = [
  {
    id: 1,
    name: 'Pé esquerdo dorso',
    shape: 'rectangle',
    y1: 300,
    y2: 350,
    x1: 75,
    x2: 115,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 2,
    name: 'Pé direito dorso',
    shape: 'rectangle',
    y1: 300,
    y2: 350,
    x1: 30,
    x2: 70,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 3,
    name: 'Mão esquerda frente',
    shape: 'rectangle',
    y1: 170,
    y2: 228,
    x1: 110,
    x2: 145,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 4,
    name: 'Mão direita frente',
    shape: 'rectangle',
    y1: 170,
    y2: 228,
    x1: 0,
    x2: 35,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 5,
    name: 'Tronco frente',
    shape: 'rectangle',
    y1: 80,
    y2: 178,
    x1: 38,
    x2: 105,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 6,
    name: 'Face',
    shape: 'rectangle',
    y1: 20,
    y2: 58,
    x1: 55,
    x2: 90,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 7,
    name: 'Couro cabeludo frente',
    shape: 'rectangle',
    y1: 0,
    y2: 18,
    x1: 48,
    x2: 95,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 8,
    name: 'Pescoço frente',
    shape: 'rectangle',
    y1: 58,
    y2: 78,
    x1: 48,
    x2: 95,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 9,
    name: 'Genital frente',
    shape: 'rectangle',
    x1: 40,
    x2: 104,
    y1: 179,
    y2: 200,

    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 10,
    name: 'Braço esquerdo frente',
    shape: 'rectangle',
    y1: 70,
    y2: 168,
    x1: 108,
    x2: 143,

    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 11,
    name: 'Braço direito frente',
    shape: 'rectangle',
    y1: 70,
    y2: 168,
    x1: 0,
    x2: 35,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 12,
    name: 'Perna esquerda frente',
    shape: 'rectangle',
    y1: 204,
    y2: 296,
    x1: 75,
    x2: 108,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 13,
    name: 'Perna direita frente',
    shape: 'rectangle',
    y1: 204,
    y2: 296,
    x1: 37,
    x2: 68,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 14,
    name: 'Pé direito planta',
    shape: 'rectangle',
    y1: 296,
    y2: 362,
    x1: 230,
    x2: 270,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 15,
    name: 'Pé esquerdo planta',
    shape: 'rectangle',
    y1: 296,
    y2: 362,
    x1: 190,
    x2: 225,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 16,
    name: 'Mão direita trás',
    shape: 'rectangle',
    y1: 168,
    y2: 225,
    x1: 265,
    x2: 300,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 17,
    name: 'Mão esquerda trás',
    shape: 'rectangle',
    y1: 168,
    y2: 225,
    x1: 155,
    x2: 190,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 18,
    name: 'Braço direito trás',
    shape: 'rectangle',
    y1: 70,
    y2: 166,
    x1: 265,
    x2: 300,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 19,
    name: 'Braço esquerdo trás',
    shape: 'rectangle',
    y1: 70,
    y2: 166,
    x1: 158,
    x2: 190,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 20,
    name: 'Tronco trás',
    shape: 'rectangle',
    y1: 78,
    y2: 190,
    x1: 192,
    x2: 262,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 21,
    name: 'Couro cabeludo trás',
    shape: 'rectangle',
    y1: 0,
    y2: 55,
    x1: 200,
    x2: 255,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 22,
    name: 'Pescoço trás',
    shape: 'rectangle',
    y1: 56,
    y2: 76,
    x1: 200,
    x2: 255,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 23,
    name: 'Perna esquerda trás',
    shape: 'rectangle',
    y1: 195,
    y2: 292,
    x1: 192,
    x2: 225,
    prefill: colorPrefill,
    fill: colorFill,
  },
  {
    id: 24,
    name: 'Perna direita trás',
    shape: 'rectangle',
    y1: 195,
    y2: 292,
    x1: 231,
    x2: 263,
    prefill: colorPrefill,
    fill: colorFill,
  },
];

export default configMap;
